//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EscanorHomeWork.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Packageinfo
    {
        public int Id { get; set; }
        public Nullable<int> PackageId { get; set; }
        public Nullable<int> OrderBy { get; set; }
        public string Title { get; set; }
    
        public virtual Package Package { get; set; }
    }
}
